### PR TITLE
Madhur dev

### PR DESCRIPTION
**Pull request by madhurjain2095**
Add gRPC and Protobuf dependency via CMake and Conan
As a bonus, also added a proto example. :-P

### CODE REVIEW

**Comment by madhurjain2095** [comment]
Apologies - can't seem to do better than what the commits show here, almost every other solution has one or the other problems with respect to exposing the generated proto files as a target/dependency to link it to the executable. Plus, the version from conan-center also requires us to use multiple cmake generators with zero advantage. I would be happy to know your thoughts on this.

**Comment by sumeetgajjar** [comment]
We can close this PR, I found a simple way to generate the protos. I have create a PR for the same, please review it.

**Comment by sumeetgajjar** [comment]
We should close this PR since the protobuf stuff is already in and delete the corresponding branch as well.

**Comment by madhurjain2095** [comment]
Yeah, I can close this PR, but I need the branch -- I have some things that I want to do with this branch after we complete the project in my free time.

**Pull request closed without merging**
